server:
  port: 8080

jwt:
  key: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==

spring:
  application:
    name: suhaeng
  security:
    user:
      name: juna
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 580473374375-d7gm5u312u0857ot8qhu2p066jsfc1q9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true
      path: /h2-console       # H2 Console ?? ??
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type: trace

# localhost/swagger-ui/index.html
swagger:
  base-package: app.server.api
  path: /api/**
  title: ??? API ?? ????.
  description: ??? API ?? ?? ????
  version: 1.0