server:
  port: 80

spring:
  application:
    name: suhaeng
  security:
    user:
      name: juna
      password: 1234
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true
      path: /h2-console       # H2 Console ?? ??

logging:
  level:
    org.hibernate.type: trace

# localhost/swagger-ui/index.html
swagger:
  base-package: app.server.api
  path: /api/**
  title: ??? API ?? ????.
  description: ??? API ?? ?? ????
  version: 1.0